/* Public portfolio content and category metadata. */
(()=>{
const collection={
  "categories": [
    "games",
    "levels",
    "technical",
    "narrative"
  ],
  "projects": [
    {
      "id": "wonderwebby",
      "file": "wonderwebby.html",
      "title": "Wonder Webby",
      "name": [
        "Wonder",
        "Webby"
      ],
      "categories": [
        "games",
        "technical"
      ],
      "engine": "Unity 6",
      "cover": "assets/wonderwebby-cover.webp",
      "index": 1,
      "metaKey": "wonderwebby.row.meta",
      "kindKey": "wonderwebby.row.kind"
    },
    {
      "id": "moon-vagrant",
      "file": "moon-vagrant.html",
      "title": "Moon Vagrant",
      "name": [
        "Moon",
        "Vagrant"
      ],
      "categories": [
        "games"
      ],
      "engine": "GDevelop 5",
      "cover": "assets/moon-vagrant-title.webp",
      "index": 2,
      "metaKey": "moon-vagrant.row.meta",
      "kindKey": "moon-vagrant.row.kind"
    },
    {
      "id": "testament",
      "file": "testament.html",
      "title": "Testament",
      "name": [
        "Testament",
        ""
      ],
      "categories": [
        "games",
        "narrative"
      ],
      "engine": "Unity",
      "cover": "assets/testament-cover.webp",
      "index": 3,
      "metaKey": "testament.row.meta",
      "kindKey": "testament.row.kind"
    },
    {
      "id": "jiangnan-water-town",
      "file": "jiangnan-water-town.html",
      "title": "Jiangnan Water Town",
      "name": [
        "Jiangnan",
        "Water Town"
      ],
      "categories": [
        "levels"
      ],
      "engine": "Unreal Engine 5.6",
      "cover": "assets/jiangnan-water-town-cover.webp",
      "kind": [
        "Hybrid FPS level",
        "Hybrid FPS 关卡"
      ],
      "meta": [
        "UNREAL / ACADEMIC LEVEL PROTOTYPE",
        "UNREAL / 学术关卡原型"
      ],
      "index": 4,
      "metaKey": "jiangnan-water-town.row.meta",
      "kindKey": "jiangnan-water-town.row.kind"
    },
    {
      "id": "fukuoka-central-street",
      "file": "fukuoka-central-street.html",
      "title": "Fukuoka Central Street",
      "name": [
        "Fukuoka",
        "Central Street"
      ],
      "categories": [
        "levels"
      ],
      "engine": "Unreal Engine",
      "cover": "assets/fukuoka-cover.webp",
      "index": 5,
      "metaKey": "fukuoka-central-street.row.meta",
      "kindKey": "fukuoka-central-street.row.kind"
    },
    {
      "id": "dragon-of-kamurocho",
      "file": "dragon-of-kamurocho.html",
      "title": "Yakuza — Dragon of Kamurocho",
      "name": [
        "Dragon of",
        "Kamurocho"
      ],
      "categories": [
        "narrative"
      ],
      "engine": "Physical tabletop",
      "cover": "assets/dragon-cover.webp",
      "index": 6,
      "metaKey": "dragon-of-kamurocho.row.meta",
      "kindKey": "dragon-of-kamurocho.row.kind"
    }
  ],
  "languages": {
    "en": {
      "collection.all": "All work",
      "collection.games": "Digital games",
      "collection.levels": "Levels & environments",
      "collection.technical": "Gameplay & technical prototypes",
      "collection.narrative": "Narrative & tabletop",
      "collection.filters": "Filter projects by category",
      "collection.empty.title": "A chapter still taking shape.",
      "collection.empty.body": "More work will join the collection as its story and contribution are documented.",
      "collection.empty.reset": "View all work",
      "collection.count.one": "{count} project",
      "collection.count.many": "{count} projects",
      "work.note": "Six projects, across digital games, environments and tabletop systems.",
      "v5.team": "Personal experiments and team projects, with my part in each documented.",
      "about.detail3": "Every case study separates the project from my contribution, with shared work and assets credited.",
      "case.idea.label": "01 / THE IDEA",
      "case.role.label": "02 / MY CONTRIBUTION",
      "case.gallery.label": "03 / A CLOSER LOOK",
      "case.credits.label": "04 / Credits & context",
      "case.scope": "CURRENT SCOPE",
      "case.process": "DESIGN & ITERATION",
      "case.shared": "PROJECT CONTEXT",
      "case.media.stills": "PROTOTYPE STILLS",
      "case.media.route": "SCENE ROUTE / DIAGRAM",
      "case.gallery.hint": "Select an image. Take a closer look.",
      "gallery.zoom": "Enlarge image",
      "lightbox.title": "Project image",
      "project.nav.gallery": "Images & diagrams",
      "project.end.note": "BACK TO THE COLLECTION",
      "case.fact.type": "PROJECT",
      "case.fact.engine": "ENGINE",
      "case.fact.focus": "FOCUS",
      "case.fact.role": "MY ROLE",
      "case.fact.status": "STATUS",
      "role.badge": "GAMEPLAY & CAMERA",
      "role.title": "The team’s game. My contribution.",
      "role.body": "I implemented hunting and feeding interactions, an adaptive wall-and-ceiling camera, contextual interaction prompts, and collision and interaction refinements in Unity.",
      "role.one": "Hunting & feeding",
      "role.two": "Camera & movement",
      "role.three": "Interaction & iteration",
      "role.hunt": "Developed prey collection and feeding interactions, with teammate support on the feeding work.",
      "role.camera": "Reworked camera behaviour on walls and ceilings and refined collision handling during traversal.",
      "role.interaction": "Added contextual prompts and controller interaction refinements, then addressed gameplay bugs through iteration.",
      "fact.role.value": "Gameplay & camera development",
      "case.webby.scope": "A playable team prototype in development. Sound, UI and gameplay polish continue.",
      "case.webby.credit": "Main menu UI, visual direction and typography were created by Leo. Environment, artwork and other systems are shared team contributions.",
      "case.webby.engine": "Unity 6",
      "wonderwebby.row.meta": "UNITY / TEAM PROJECT",
      "wonderwebby.row.kind": "Exploration",
      "moon-vagrant.row.meta": "GDEVELOP / SOLO PROTOTYPE",
      "moon-vagrant.row.kind": "Space survival",
      "moon-vagrant.tagline": "A small ship. A crowded sky.",
      "moon-vagrant.status": "PLAYABLE PROTOTYPE",
      "moon-vagrant.mediaCaption": "The exported prototype’s title screen.",
      "moon-vagrant.ideaTitle": "Survival, one decision at a time.",
      "moon-vagrant.lead": "A 2D space shooter built around movement, pressure and limited resources.",
      "moon-vagrant.body": "Pilot a small spacecraft through asteroids and enemy fire. Mouse-directed movement and shooting work alongside sprint and shockwave abilities, while health, fuel and weapon heat create competing demands. A comic-style introduction leads into the combat encounter.",
      "moon-vagrant.scope": "The browser preview and Windows export demonstrate a compact combat slice. Full multi-level progression, advanced upgrades and complete story delivery are outside this prototype’s scope.",
      "moon-vagrant.roleTitle": "From concept to a playable slice.",
      "moon-vagrant.roleBody": "I developed the concept and prototype scope, implemented the game in GDevelop, prepared playtests, organised observations and analysed the findings.",
      "moon-vagrant.galleryTitle": "A story before the pressure.",
      "moon-vagrant.credits": "Built with GDevelop. These screenshots show the exported prototype and its existing artwork; the GDevelop watermark is retained. The development contribution described here does not claim authorship of every illustration or audio asset.",
      "moon-vagrant.index": "PROJECT 02 / MOON VAGRANT",
      "moon-vagrant.fact.0": "Individual project",
      "moon-vagrant.fact.1": "GDevelop 5",
      "moon-vagrant.fact.2": "Combat & readability",
      "moon-vagrant.fact.3": "Concept, implementation & playtesting",
      "moon-vagrant.fact.4": "Combat slice / v1.0.0",
      "moon-vagrant.steps.0.title": "Move & evade",
      "moon-vagrant.steps.0.body": "Read incoming threats and use sprint to change position.",
      "moon-vagrant.steps.1.title": "Shoot & manage",
      "moon-vagrant.steps.1.body": "Attack while keeping track of heat, health and movement resources.",
      "moon-vagrant.steps.2.title": "Survive & retry",
      "moon-vagrant.steps.2.body": "Use shockwave to respond to pressure, then learn from the encounter.",
      "moon-vagrant.roles.0.title": "Combat rules",
      "moon-vagrant.roles.0.body": "Implemented mouse-directed movement, shooting, sprint and shockwave interactions in the prototype.",
      "moon-vagrant.roles.1.title": "Story & interface",
      "moon-vagrant.roles.1.body": "Connected the title screen and comic introduction to the combat scene and resource feedback.",
      "moon-vagrant.roles.2.title": "Playtest observations",
      "moon-vagrant.roles.2.body": "Identified improvements to onboarding, resource HUD, ability feedback and boss pacing. These are iteration proposals, rather than verified completed changes.",
      "moon-vagrant.gallery.0": "The comic-style introduction in the prototype.",
      "moon-vagrant.gallery.1": "An in-game frame with the movement hint and resource HUD.",
      "moon-vagrant.loopLabel": "THE CORE LOOP",
      "jiangnan-water-town.row.meta": "UNREAL / ACADEMIC LEVEL PROTOTYPE",
      "jiangnan-water-town.row.kind": "Hybrid FPS level",
      "jiangnan-water-town.tagline": "Waterways, contested crossings, and a journey to the other shore.",
      "jiangnan-water-town.status": "ACADEMIC LEVEL PROTOTYPE",
      "jiangnan-water-town.mediaCaption": "Actual project screenshot: Jiangnan architecture and waterways.",
      "jiangnan-water-town.ideaTitle": "One ritual. Two objective phases.",
      "jiangnan-water-town.lead": "An Overwatch-inspired Hybrid FPS level, designed and assembled in Unreal Engine 5.6.",
      "jiangnan-water-town.body": "The design starts with a contested altar at Point A, then proposes escorting a Spirit Boat across stone bridges, through flood-damaged ruins and toward the Gate to the Other Shore. Waterways divide the space; interiors, stairs and high ground create alternative approaches. The capture-to-payload structure connects the planned objectives to an environmental story about guiding trapped spirits out of a flooded Jiangnan town.",
      "jiangnan-water-town.scope": "The Unreal project, authored design document and screenshots confirm a built level environment and documented Hybrid flow. Capture progression, payload behaviour, networking and competitive balance are design intentions rather than verified complete multiplayer systems. This is an independent academic prototype inspired by Overwatch, not an official map.",
      "jiangnan-water-town.roleTitle": "From a top-down plan to a navigable space.",
      "jiangnan-water-town.roleBody": "I developed the level concept and top-down layout, then assembled the map in Unreal. My work connects the objective sequence, main and flank routes, elevation, sightline control and environmental landmarks. I adjusted spatial widths and visual obstructions from the first-person perspective rather than treating the diagram as a final geometry specification.",
      "jiangnan-water-town.galleryTitle": "The route, in the real project.",
      "jiangnan-water-town.credits": "Level concept, layout, documentation and environment assembly: Rong Guo. The project uses Unreal starter content and third-party environment assets, including Traditional Chinese Style Park; these screenshots do not claim original authorship of every model, texture or system. Overwatch is referenced as a design influence only; the prototype is not affiliated with or endorsed by Blizzard Entertainment. Private coursework documents and source files are not published.",
      "jiangnan-water-town.index": "PROJECT 04 / JIANGNAN WATER TOWN",
      "jiangnan-water-town.fact.0": "Individual academic project",
      "jiangnan-water-town.fact.1": "Unreal Engine 5.6",
      "jiangnan-water-town.fact.2": "Hybrid FPS spatial design",
      "jiangnan-water-town.fact.3": "Level design & environment assembly",
      "jiangnan-water-town.fact.4": "Built map / documented objective flow",
      "jiangnan-water-town.loopLabel": "PLANNED OBJECTIVE FLOW",
      "jiangnan-water-town.steps.0.title": "Point A / The altar",
      "jiangnan-water-town.steps.0.body": "Plan a capture phase around the altar, approached through the main street, interiors and flanks.",
      "jiangnan-water-town.steps.1.title": "Point B / Flooded ruins",
      "jiangnan-water-town.steps.1.body": "Plan the Spirit Boat route across a stone bridge, with corners and structures breaking extended sightlines.",
      "jiangnan-water-town.steps.2.title": "Point C / The other shore",
      "jiangnan-water-town.steps.2.body": "Plan a final approach through waterways and a secondary land route toward the ending landmark.",
      "jiangnan-water-town.roles.0.title": "Objective layout & route choice",
      "jiangnan-water-town.roles.0.body": "Translate the capture-to-payload design into linked spaces, with direct main routes and longer flanking options.",
      "jiangnan-water-town.roles.1.title": "Elevation & sightlines",
      "jiangnan-water-town.roles.1.body": "Use bridges, corners, building interiors, stairs and upper floors to shape sightlines and access to high ground.",
      "jiangnan-water-town.roles.2.title": "Environment & wayfinding",
      "jiangnan-water-town.roles.2.body": "Assemble water-town spaces and landmarks, including the altar, stone fish and final gate, to connect navigation with the spirit-procession narrative.",
      "jiangnan-water-town.gallery.0": "Point A: the capture area and surrounding water-town architecture.",
      "jiangnan-water-town.gallery.1": "Stone bridge and stone-fish landmarks between local combat spaces.",
      "jiangnan-water-town.gallery.2": "The Gate to the Other Shore, a clear final destination in the environment.",
      "jiangnan-water-town.gallery.3": "Original top-down layout planning spawns, routes, water and elevation.",
      "play.nav": "Play here",
      "play.label": "BROWSER PREVIEW",
      "play.title": "Take the controls.",
      "play.note": "Desktop mouse and keyboard required. About 25 MB loads when you choose Play. This preview keeps sound effects and omits background music.",
      "play.load": "Play Moon Vagrant",
      "play.fullscreen": "Fullscreen",
      "play.exit": "Exit game",
      "play.controls": "Click the game to focus. Choose Start, click to reveal the comic, then press Space or scroll to advance and select the final button. In combat: mouse to move, left click to shoot, right click to dash. Escape or Exit game closes the preview. Leaving the game pauses it.",
      "play.audioHint": "To hear effects, enable Sound, then click inside the game. Touch controls are not adapted; use a desktop browser.",
      "play.idle": "Ready when you are.",
      "play.loading": "Loading the game…",
      "play.ready": "Loaded. Click inside the game to begin.",
      "play.playing": "Game active.",
      "play.paused": "Paused. Click inside the game to resume.",
      "play.error": "The game could not load. Check your connection, then try again.",
      "play.retry": "Try again",
      "play.soundOff": "Sound off",
      "play.soundOn": "Sound on",
      "play.fullscreenError": "Fullscreen is unavailable here. You can continue in the page.",
      "play.closed": "Game closed. You can load a fresh session.",
      "play.local": "Open this page through a local web server or the published website to play.",
      "case.fact.medium": "MEDIUM",
      "testament.row.meta": "UNITY / NARRATIVE PROTOTYPE",
      "testament.row.kind": "Story & interaction",
      "testament.tagline": "A diary, a journey, and questions without easy answers.",
      "testament.status": "NARRATIVE PROTOTYPE",
      "testament.mediaCaption": "A neutral exploration scene from the existing Unity prototype.",
      "testament.ideaTitle": "Discover the story through the world.",
      "testament.lead": "A text-driven Unity narrative prototype combining conversations, scene exploration and a flight segment.",
      "testament.body": "The player follows Criki and scientist Haruto on a document-delivery journey. NPC conversations and readable objects reveal fragments of the world and its past. The project explores questions of existence and meaning through a hand-sketched visual direction, with chapter and laboratory interaction flows documented alongside the prototype.",
      "testament.scope": "The portfolio records prototype scenes and dialogue, exploration and flying functions. Inventory-based item delivery is explicitly described as not yet implemented. Six completed chapters, a complete playthrough and persistent save behaviour have not been verified; the flowcharts describe the intended structure.",
      "testament.roleTitle": "Connect narrative beats with interaction.",
      "testament.roleBody": "My work covers narrative and interaction design, scene planning and Unity prototype development. The portfolio documents chapter-sequence organisation and dialogue choices, alongside exploration and flying logic. This case presents that development process without treating every planned feature as finished.",
      "testament.galleryTitle": "From scene ideas to a narrative structure.",
      "testament.credits": "Created in Unity; Photoshop and Illustrator are listed in the project materials. Literary influences include Dostoevsky and Nietzsche. The images are selected prototype views and design excerpts, rather than the full source documents. Referenced games, images and third-party assets remain their creators’ work; the development contribution does not claim authorship of every referenced asset.",
      "testament.fact.0": "Narrative game prototype",
      "testament.fact.1": "Unity",
      "testament.fact.2": "Dialogue & discovery",
      "testament.fact.3": "Story, interaction & prototype development",
      "testament.fact.4": "Prototype / documented scene flow",
      "testament.loopLabel": "NARRATIVE INTERACTION FLOW",
      "testament.steps.0.title": "Explore a scene",
      "testament.steps.0.body": "Move through a scene and locate people or readable objects.",
      "testament.steps.1.title": "Read & respond",
      "testament.steps.1.body": "Use dialogue choices and text interactions to uncover context.",
      "testament.steps.2.title": "Follow the sequence",
      "testament.steps.2.body": "Link conversations, transitions and activity segments through the planned chapter structure.",
      "testament.roles.0.title": "Narrative structure",
      "testament.roles.0.body": "Plan the story’s chapter and scene sequence, with separate dialogue and laboratory interaction flows.",
      "testament.roles.1.title": "Interaction logic",
      "testament.roles.1.body": "Work on dialogue choices, left/right exploration, object reading and the flight segment shown in the portfolio.",
      "testament.roles.2.title": "Scene & visual planning",
      "testament.roles.2.body": "Develop scene sketches and connect the paper-like visual treatment with the prototype’s interface and exploration views.",
      "testament.gallery.0": "The prototype’s main menu, shown within the Unity Game view.",
      "testament.gallery.1": "Original chapter and laboratory interaction planning. These diagrams do not establish completed chapters.",
      "testament.gallery.2": "Scene sketches exploring the arrangement of interior spaces.",
      "testament.index": "PROJECT 03 / TESTAMENT",
      "fukuoka-central-street.row.meta": "UNREAL / ENVIRONMENT STUDY",
      "fukuoka-central-street.row.kind": "Street & interior design",
      "fukuoka-central-street.tagline": "Dusk outside. A lived-in space within.",
      "fukuoka-central-street.status": "ENVIRONMENT PROTOTYPE",
      "fukuoka-central-street.mediaCaption": "An actual Unreal scene view from the Fukuoka Central Street project.",
      "fukuoka-central-street.ideaTitle": "Build a neighbourhood from its landmarks.",
      "fukuoka-central-street.lead": "An Unreal environment study combining a Fukuoka-inspired street district with an accessible traditional Japanese home.",
      "fukuoka-central-street.body": "The project draws on Nakasu and Hakata streets and the urban spaces of Yakuza 5. White-box layouts develop into a rainy dusk neighbourhood with a bathhouse, restaurant, arcade-inspired landmark and connecting streets. The home interior takes structural cues from the Hazuki Residence in Shenmue, while props and lighting give each space a distinct atmosphere.",
      "fukuoka-central-street.scope": "The portfolio shows street and interior assembly, blockout iteration, Sequencer camera work and an NPC navigation setup. These are documented environment and implementation studies; a complete gameplay loop, browser build and live NPC behaviour have not been verified in this case.",
      "fukuoka-central-street.roleTitle": "Shape the space, then compose the view.",
      "fukuoka-central-street.roleBody": "My portfolio work focuses on level layout, environment assembly and scene presentation. It records the progression from white boxes to dressed streets and interiors, plus camera sequencing and navigation setup. Referenced layouts and third-party character or environment models are credited separately from that work.",
      "fukuoka-central-street.galleryTitle": "Blockout, assembly, and presentation.",
      "fukuoka-central-street.credits": "This is a non-commercial environment study. Yakuza / Like a Dragon and Shenmue are documented visual and spatial references; their settings, characters and referenced assets remain third-party work. The project uses assembled character and environment models and does not claim original modelling of every asset. Selected captures show the authored Unreal scene and its process, rather than redistributing model files. No official affiliation or endorsement is implied.",
      "fukuoka-central-street.fact.0": "Environment study",
      "fukuoka-central-street.fact.1": "Unreal Engine",
      "fukuoka-central-street.fact.2": "Streets, interiors & atmosphere",
      "fukuoka-central-street.fact.3": "Layout & environment assembly",
      "fukuoka-central-street.fact.4": "Built scene / process portfolio",
      "fukuoka-central-street.loopLabel": "ENVIRONMENT DEVELOPMENT",
      "fukuoka-central-street.steps.0.title": "Block out",
      "fukuoka-central-street.steps.0.body": "Establish the street network, building masses and the home’s interior structure.",
      "fukuoka-central-street.steps.1.title": "Dress & light",
      "fukuoka-central-street.steps.1.body": "Replace simple forms with assembled assets, signage and rainy dusk lighting.",
      "fukuoka-central-street.steps.2.title": "Present the space",
      "fukuoka-central-street.steps.2.body": "Use cinematic camera passes and document the NPC navigation configuration.",
      "fukuoka-central-street.roles.0.title": "Street & interior layout",
      "fukuoka-central-street.roles.0.body": "Develop blockout layouts and organise exterior landmarks and connected residential spaces.",
      "fukuoka-central-street.roles.1.title": "Environment assembly",
      "fukuoka-central-street.roles.1.body": "Arrange third-party models and props, replace blockout assets and develop the project’s dusk atmosphere.",
      "fukuoka-central-street.roles.2.title": "Cameras & navigation",
      "fukuoka-central-street.roles.2.body": "Document Sequencer camera tracks and an AI-controller, NavMesh and behaviour-tree setup for local NPC movement.",
      "fukuoka-central-street.gallery.0": "An early white-box street view, before the environment assets were assembled.",
      "fukuoka-central-street.gallery.1": "The assembled home interior in the Unreal editor; its layout references the Hazuki Residence in Shenmue.",
      "fukuoka-central-street.gallery.2": "An excerpt of the project’s outdoor Sequencer camera timeline.",
      "fukuoka-central-street.gallery.3": "Documented NPC Blueprint and behaviour-tree setup, presented as implementation evidence rather than a live behaviour test.",
      "fukuoka-central-street.index": "PROJECT 05 / FUKUOKA CENTRAL STREET",
      "dragon-of-kamurocho.row.meta": "TABLETOP / NON-COMMERCIAL STUDY",
      "dragon-of-kamurocho.row.kind": "Territory & economy",
      "dragon-of-kamurocho.tagline": "Every territory changes the next decision.",
      "dragon-of-kamurocho.status": "PHYSICAL TABLETOP PROTOTYPE",
      "dragon-of-kamurocho.mediaCaption": "The actual physical prototype map, with territory markers, cards and play money.",
      "dragon-of-kamurocho.ideaTitle": "Connect territory, money and strength.",
      "dragon-of-kamurocho.lead": "A non-commercial, fan-inspired strategy board-game study using Yakuza / Like a Dragon’s Kamurocho setting.",
      "dragon-of-kamurocho.body": "Players build income through territories, invest in development and use character strength to contest rival holdings. Regional risk and neutral-event timing interrupt that expansion, while a planned Millennium Tower showdown gives the economy a final objective. The design adapts territory-annexation ideas from Rurik: Dawn of Kiev and links them more closely to combat values and money.",
      "dragon-of-kamurocho.scope": "A physical prototype, rules flow and component development are documented. The portfolio states a target of 2–3 players and approximately 20 minutes; these are design specifications, not verified session measurements. This is an unofficial, non-commercial study prototype, and does not claim an original Yakuza IP or provide a licensed print-and-play release.",
      "dragon-of-kamurocho.roleTitle": "Turn connected systems into table decisions.",
      "dragon-of-kamurocho.roleBody": "My work covers the rules and system design, prototype map and component organisation. I linked territory control, character battle values, income and neutral-event risk, then prepared physical materials and rule diagrams to make those relationships visible at the table. The character setting and borrowed artwork remain third-party content.",
      "dragon-of-kamurocho.galleryTitle": "The rules become physical.",
      "dragon-of-kamurocho.credits": "Yakuza / Like a Dragon supplies the fan-inspired setting and character references; its IP and character artwork remain their respective rights holders’ work. Rurik: Dawn of Kiev is the documented territory-annexation design reference. Commercial playing-card and play-money components and other borrowed visual assets are not claimed as original work. These selected prototype photographs and flow diagrams document learning and system design; they do not grant a licence to reproduce the IP or materials. No official affiliation is implied.",
      "dragon-of-kamurocho.fact.0": "Board-game prototype",
      "dragon-of-kamurocho.fact.1": "Physical tabletop",
      "dragon-of-kamurocho.fact.2": "Territory, economy & risk",
      "dragon-of-kamurocho.fact.3": "Rules, systems & prototype components",
      "dragon-of-kamurocho.fact.4": "2–3 players / documented target",
      "dragon-of-kamurocho.loopLabel": "DOCUMENTED TURN STRUCTURE",
      "dragon-of-kamurocho.steps.0.title": "Build income",
      "dragon-of-kamurocho.steps.0.body": "Choose starting territory and use its resources to develop funds and capabilities.",
      "dragon-of-kamurocho.steps.1.title": "Invest & annex",
      "dragon-of-kamurocho.steps.1.body": "Connect money and character strength to territory development and contested ownership.",
      "dragon-of-kamurocho.steps.2.title": "Resolve risk",
      "dragon-of-kamurocho.steps.2.body": "Track neutral-event rounds and regional risk while progressing toward the planned final showdown.",
      "dragon-of-kamurocho.roles.0.title": "Rules & economy",
      "dragon-of-kamurocho.roles.0.body": "Link territory income, capital spending, character strength and annexation conditions into one decision structure.",
      "dragon-of-kamurocho.roles.1.title": "Risk & timing",
      "dragon-of-kamurocho.roles.1.body": "Design regional risk levels, neutral-event checks and counters that make event timing visible.",
      "dragon-of-kamurocho.roles.2.title": "Physical prototyping",
      "dragon-of-kamurocho.roles.2.body": "Prepare the map, card and marker arrangement, rule flows and prototype materials shown in the portfolio.",
      "dragon-of-kamurocho.gallery.0": "The original turn-flow diagram connecting actions, events, annexation and the planned final showdown.",
      "dragon-of-kamurocho.gallery.1": "An early paper prototype using physical counters to track regional event timing.",
      "dragon-of-kamurocho.gallery.2": "Assembled prototype components, including cards, markers, dice and third-party play-money materials.",
      "dragon-of-kamurocho.index": "PROJECT 06 / YAKUZA — DRAGON OF KAMUROCHO"
    },
    "zh": {
      "collection.all": "全部作品",
      "collection.games": "数字游戏",
      "collection.levels": "关卡与场景",
      "collection.technical": "玩法与技术原型",
      "collection.narrative": "叙事与桌游",
      "collection.filters": "按类别筛选作品",
      "collection.empty.title": "这一章，仍在整理中。",
      "collection.empty.body": "待作品背景与个人贡献整理清楚后，这里会加入更多作品。",
      "collection.empty.reset": "查看全部作品",
      "collection.count.one": "{count} 个项目",
      "collection.count.many": "{count} 个项目",
      "work.note": "六个项目，涵盖数字游戏、环境场景与桌游系统。",
      "v5.team": "个人探索与团队项目，分别记录我在其中承担的工作。",
      "about.detail3": "每个案例都分别介绍作品和我的贡献，并注明团队工作与使用的素材。",
      "case.idea.label": "01 / 作品构想",
      "case.role.label": "02 / 我的贡献",
      "case.gallery.label": "03 / 近看作品",
      "case.credits.label": "04 / 署名与背景",
      "case.scope": "当前范围",
      "case.process": "设计与迭代",
      "case.shared": "项目背景",
      "case.media.stills": "原型截图",
      "case.media.route": "场景路线 / 示意图",
      "case.gallery.hint": "选择图片，查看细节。",
      "gallery.zoom": "放大图片",
      "lightbox.title": "项目图片",
      "project.nav.gallery": "图片与图示",
      "project.end.note": "回到作品集",
      "case.fact.type": "项目形式",
      "case.fact.engine": "引擎",
      "case.fact.focus": "设计重点",
      "case.fact.role": "我的职责",
      "case.fact.status": "当前状态",
      "role.badge": "玩法与相机",
      "role.title": "团队的作品，我的贡献。",
      "role.body": "我在 Unity 中实现捕猎与喂食交互、适应墙壁与天花板的相机、情境交互提示，并完善碰撞和交互体验。",
      "role.one": "捕猎与喂食",
      "role.two": "相机与移动",
      "role.three": "交互与迭代",
      "role.hunt": "开发猎物收集和喂食交互，喂食部分有队友协作。",
      "role.camera": "重做墙壁与天花板上的相机行为，并改善移动过程中的碰撞处理。",
      "role.interaction": "加入情境提示、完善手柄交互，并在迭代中修正玩法问题。",
      "fact.role.value": "玩法与相机开发",
      "case.webby.scope": "开发中的团队可玩原型，音效、界面和玩法仍在打磨。",
      "case.webby.credit": "主菜单界面、视觉方向和字体设计由 Leo 完成；环境、美术和其他系统属于团队共同成果。",
      "case.webby.engine": "Unity 6",
      "wonderwebby.row.meta": "UNITY / 团队项目",
      "wonderwebby.row.kind": "探索",
      "moon-vagrant.row.meta": "GDEVELOP / 个人原型",
      "moon-vagrant.row.kind": "太空生存",
      "moon-vagrant.tagline": "一艘小船，一片危机四伏的天空。",
      "moon-vagrant.status": "可玩原型",
      "moon-vagrant.mediaCaption": "导出原型的标题画面。",
      "moon-vagrant.ideaTitle": "在每一次选择中求生。",
      "moon-vagrant.lead": "围绕移动、压力与有限资源构建的 2D 太空射击原型。",
      "moon-vagrant.body": "驾驶小型飞船穿越小行星与敌方火力。鼠标移动与射击配合冲刺、冲击波能力，生命、燃料与武器热量形成不同的资源压力；漫画式开场引入战斗遭遇。",
      "moon-vagrant.scope": "浏览器试玩与 Windows 导出版本展示一个紧凑的战斗切片，未覆盖完整多关卡进程、进阶升级或完整故事。",
      "moon-vagrant.roleTitle": "从概念，到可玩的切片。",
      "moon-vagrant.roleBody": "我完成概念与原型范围设计，在 GDevelop 中实现游戏，并准备试玩、整理观察记录和分析结果。",
      "moon-vagrant.galleryTitle": "压力来临前，故事先开始。",
      "moon-vagrant.credits": "使用 GDevelop 制作。截图来自导出原型，保留原有画面与 GDevelop 水印；此处的开发贡献不代表所有插画或音频素材均为本人原创。",
      "moon-vagrant.index": "项目 02 / Moon Vagrant",
      "moon-vagrant.fact.0": "个人项目",
      "moon-vagrant.fact.1": "GDevelop 5",
      "moon-vagrant.fact.2": "战斗与可读性",
      "moon-vagrant.fact.3": "概念、实现与试玩分析",
      "moon-vagrant.fact.4": "战斗切片 / v1.0.0",
      "moon-vagrant.steps.0.title": "移动与闪避",
      "moon-vagrant.steps.0.body": "观察来袭威胁，用冲刺改变位置。",
      "moon-vagrant.steps.1.title": "射击与管理",
      "moon-vagrant.steps.1.body": "进攻时关注热量、生命与移动资源。",
      "moon-vagrant.steps.2.title": "生存与重试",
      "moon-vagrant.steps.2.body": "用冲击波应对压力，从遭遇中学习并重试。",
      "moon-vagrant.roles.0.title": "战斗规则",
      "moon-vagrant.roles.0.body": "在原型中实现鼠标控制移动、射击、冲刺和冲击波交互。",
      "moon-vagrant.roles.1.title": "叙事与界面",
      "moon-vagrant.roles.1.body": "连接标题画面、漫画开场、战斗场景与资源反馈。",
      "moon-vagrant.roles.2.title": "试玩观察",
      "moon-vagrant.roles.2.body": "识别引导、资源 HUD、能力反馈和 Boss 节奏的改进方向。这些是迭代建议，尚不能视为已验证完成的修改。",
      "moon-vagrant.gallery.0": "原型中的漫画式开场。",
      "moon-vagrant.gallery.1": "包含移动提示与资源 HUD 的实机画面。",
      "moon-vagrant.loopLabel": "核心循环",
      "jiangnan-water-town.row.meta": "UNREAL / 学术关卡原型",
      "jiangnan-water-town.row.kind": "Hybrid FPS 关卡",
      "jiangnan-water-town.tagline": "水巷、争夺中的石桥，以及通往彼岸的旅程。",
      "jiangnan-water-town.status": "学术关卡原型",
      "jiangnan-water-town.mediaCaption": "真实项目截图：江南建筑与水道。",
      "jiangnan-water-town.ideaTitle": "一场仪式，两个目标阶段。",
      "jiangnan-water-town.lead": "在 Unreal Engine 5.6 中设计并搭建的 Overwatch-inspired Hybrid FPS 关卡。",
      "jiangnan-water-town.body": "设计从 A 点祭坛的争夺开始，随后规划护送灵舟经过石桥、洪灾废墟，抵达彼岸之门。水道划分空间，建筑内部、楼梯与高地提供不同进攻路径。占点转运载的结构将目标规划与环境叙事连接起来：引导受困的亡灵离开被洪水摧毁的江南古城。",
      "jiangnan-water-town.scope": "Unreal 工程、本人设计文档与截图确认了已搭建的关卡环境和 Hybrid 流程规划。占点推进、运载行为、联网与竞技平衡属于设计意图，尚未验证为完整多人系统。这是受 Overwatch 启发的独立学术原型，并非官方地图。",
      "jiangnan-water-town.roleTitle": "从俯视规划，到可行走的空间。",
      "jiangnan-water-town.roleBody": "我负责关卡概念与俯视布局规划，并在 Unreal 中搭建地图，将目标顺序、主路与侧翼、高差、视线控制和环境地标连接起来。我从第一人称视角调整空间宽度与视线遮挡，使二维规划转化为实际关卡空间。",
      "jiangnan-water-town.galleryTitle": "在真实地图中，读懂路线。",
      "jiangnan-water-town.credits": "关卡概念、布局、设计文档与环境搭建：Rong Guo。项目使用 Unreal 初始内容及第三方环境素材，包括 Traditional Chinese Style Park；截图不代表所有模型、纹理或系统均由本人原创。Overwatch 仅作为设计参考，本原型与 Blizzard Entertainment 无官方关联或认可。课程原文及工程源码未公开。",
      "jiangnan-water-town.index": "项目 04 / 江南水乡",
      "jiangnan-water-town.fact.0": "个人学术项目",
      "jiangnan-water-town.fact.1": "Unreal Engine 5.6",
      "jiangnan-water-town.fact.2": "Hybrid FPS 空间设计",
      "jiangnan-water-town.fact.3": "关卡设计与环境搭建",
      "jiangnan-water-town.fact.4": "已搭建地图 / 目标流程规划",
      "jiangnan-water-town.loopLabel": "目标流程规划",
      "jiangnan-water-town.steps.0.title": "A 点 / 祭坛",
      "jiangnan-water-town.steps.0.body": "围绕祭坛规划占点阶段，通过主街、建筑内部与侧翼争夺空间。",
      "jiangnan-water-town.steps.1.title": "B 点 / 洪灾废墟",
      "jiangnan-water-town.steps.1.body": "规划灵舟经过石桥的路线，以转角与建筑限制过长视线。",
      "jiangnan-water-town.steps.2.title": "C 点 / 彼岸之门",
      "jiangnan-water-town.steps.2.body": "规划水道与次要陆路通往终点地标的最后推进阶段。",
      "jiangnan-water-town.roles.0.title": "目标布局与路线选择",
      "jiangnan-water-town.roles.0.body": "将占点转运载的设计落实为空间连接，以直接主路和较长侧翼形成路线选择。",
      "jiangnan-water-town.roles.1.title": "高差与视线",
      "jiangnan-water-town.roles.1.body": "用石桥、转角、建筑内部、楼梯与二层空间组织视线及高地的可达路径。",
      "jiangnan-water-town.roles.2.title": "环境与方向引导",
      "jiangnan-water-town.roles.2.body": "搭建水乡空间与祭坛、石鱼、终点门等地标，将方向引导与送灵叙事结合。",
      "jiangnan-water-town.gallery.0": "A 点：占点区域及周边水乡建筑。",
      "jiangnan-water-town.gallery.1": "连接局部战斗空间的石桥与石鱼地标。",
      "jiangnan-water-town.gallery.2": "彼岸之门：环境中明确的最终目标地标。",
      "jiangnan-water-town.gallery.3": "原始俯视规划：出生点、路线、水道与高差。",
      "play.nav": "在此游玩",
      "play.label": "浏览器试玩",
      "play.title": "接过操控权。",
      "play.note": "需要桌面电脑的鼠标与键盘。点击游玩后加载约 25 MB 内容。此试玩保留音效，移除了背景音乐。",
      "play.load": "游玩 Moon Vagrant",
      "play.fullscreen": "全屏",
      "play.exit": "退出游戏",
      "play.controls": "点击游戏画面获得焦点。选择 Start，点击显示漫画，再按空格或滚动推进，点击最后的按钮进入战斗。战斗操作：鼠标控制移动，左键射击，右键冲刺。按 Esc 或点击“退出游戏”关闭试玩。离开游戏时自动暂停。",
      "play.audioHint": "开启声音后，再点击游戏画面即可听到音效。尚未适配触屏操作，请使用桌面浏览器。",
      "play.idle": "准备好后即可开始。",
      "play.loading": "正在加载游戏…",
      "play.ready": "加载完成。点击游戏画面开始。",
      "play.playing": "游戏运行中。",
      "play.paused": "已暂停。点击游戏画面继续。",
      "play.error": "游戏加载失败。请检查网络后重试。",
      "play.retry": "重新尝试",
      "play.soundOff": "声音关闭",
      "play.soundOn": "声音开启",
      "play.fullscreenError": "此处无法启用全屏，可继续在页面内游玩。",
      "play.closed": "游戏已关闭，可重新加载新一局。",
      "play.local": "请通过本地网页服务器或已发布的网站打开此页游玩。",
      "case.fact.medium": "载体",
      "testament.row.meta": "UNITY / 叙事原型",
      "testament.row.kind": "叙事与交互",
      "testament.tagline": "一本日记，一段旅程，一些没有简单答案的问题。",
      "testament.status": "叙事原型",
      "testament.mediaCaption": "现有 Unity 原型中的探索场景。",
      "testament.ideaTitle": "从世界中发现故事。",
      "testament.lead": "一个以文字互动为主的 Unity 叙事原型，结合对话、场景探索与飞行片段。",
      "testament.body": "玩家跟随 Criki 与科学家 Haruto 踏上运送文件的旅程，通过 NPC 对话及可阅读物件了解世界与过去。作品以手绘草图式的视觉方向探讨存在与意义，并记录了章节推进及实验室交互的流程规划。",
      "testament.scope": "作品资料记录了原型场景，以及对话、探索和飞行功能。基于背包的物品交付明确标为尚未实现。六章完整完成、全流程通关及存档持久性尚未核实；流程图呈现的是结构规划。",
      "testament.roleTitle": "把叙事节点与交互连接起来。",
      "testament.roleBody": "我的工作涵盖叙事与交互设计、场景规划及 Unity 原型开发。作品资料记录了章节序列组织、对话选项，以及探索和飞行逻辑。本案例呈现这些开发过程，区分已记录的原型工作与规划功能。",
      "testament.galleryTitle": "从场景草图到叙事结构。",
      "testament.credits": "使用 Unity 开发，作品资料也列出了 Photoshop 与 Illustrator。文学思想参考包括陀思妥耶夫斯基与尼采。展示图仅为原型画面及必要的设计摘图，未公开完整源资料。参考游戏、图片及第三方素材仍属于各自创作者；开发贡献不代表所有参考素材均由本人原创。",
      "testament.fact.0": "叙事游戏原型",
      "testament.fact.1": "Unity",
      "testament.fact.2": "对话与探索",
      "testament.fact.3": "叙事、交互与原型开发",
      "testament.fact.4": "原型 / 场景流程记录",
      "testament.loopLabel": "叙事交互流程",
      "testament.steps.0.title": "探索场景",
      "testament.steps.0.body": "在场景中移动，寻找人物与可阅读物件。",
      "testament.steps.1.title": "阅读与回应",
      "testament.steps.1.body": "通过对话选项及文字交互了解背景。",
      "testament.steps.2.title": "跟随叙事序列",
      "testament.steps.2.body": "依照章节规划连接对话、转场与活动片段。",
      "testament.roles.0.title": "叙事结构",
      "testament.roles.0.body": "规划故事章节与场景序列，分别组织对话及实验室交互流程。",
      "testament.roles.1.title": "交互逻辑",
      "testament.roles.1.body": "开发资料中展示的对话选项、左右探索、物件阅读与飞行片段。",
      "testament.roles.2.title": "场景与视觉规划",
      "testament.roles.2.body": "制作场景草图，将纸面手绘式视觉方向与原型界面及探索画面连接。",
      "testament.gallery.0": "Unity Game 视图中的原型主菜单。",
      "testament.gallery.1": "原始章节与实验室交互规划；这些图示不代表章节已经完整完成。",
      "testament.gallery.2": "探索室内空间安排的场景草图。",
      "testament.index": "项目 03 / Testament",
      "fukuoka-central-street.row.meta": "UNREAL / 场景学习项目",
      "fukuoka-central-street.row.kind": "街区与室内设计",
      "fukuoka-central-street.tagline": "街外黄昏，屋内生活。",
      "fukuoka-central-street.status": "场景原型",
      "fukuoka-central-street.mediaCaption": "Fukuoka Central Street 项目中的真实 Unreal 场景画面。",
      "fukuoka-central-street.ideaTitle": "从地标组织一片街区。",
      "fukuoka-central-street.lead": "一个 Unreal 场景学习项目，将福冈风格街区与可进入的传统日式住宅结合。",
      "fukuoka-central-street.body": "作品参考中洲与博多街道，以及《如龙 5》的城市空间。从白盒布局发展为雨中黄昏街区，以浴场、餐馆、街机风格地标及连接街道组织环境。住宅内部参考《莎木》芭月家的空间结构，并通过陈设与灯光塑造不同空间的氛围。",
      "fukuoka-central-street.scope": "作品资料展示了街道及室内场景搭建、白盒迭代、Sequencer 镜头工作与 NPC 导航配置。本案例记录环境及实现过程，未核实完整玩法循环、浏览器构建或实时 NPC 行为。",
      "fukuoka-central-street.roleTitle": "先塑造空间，再组织视角。",
      "fukuoka-central-street.roleBody": "我的作品工作重点是关卡布局、环境搭建与场景呈现。资料记录了从白盒到街道与室内陈设的过程，以及镜头序列和导航配置。参考布局、第三方角色及环境模型与这些工作分别说明。",
      "fukuoka-central-street.galleryTitle": "白盒、搭建与呈现。",
      "fukuoka-central-street.credits": "这是非商业场景学习项目。《如龙 / Like a Dragon》与《莎木》是资料中记录的视觉及空间参考；其世界、角色及参考素材仍属于第三方作品。项目使用组装的角色与环境模型，不声称所有资产均由本人原创建模。所选图片展示搭建的 Unreal 场景及过程，未分发模型文件，也不表示官方关联或认可。",
      "fukuoka-central-street.fact.0": "场景学习项目",
      "fukuoka-central-street.fact.1": "Unreal Engine",
      "fukuoka-central-street.fact.2": "街区、室内与氛围",
      "fukuoka-central-street.fact.3": "布局与环境搭建",
      "fukuoka-central-street.fact.4": "已搭建场景 / 过程记录",
      "fukuoka-central-street.loopLabel": "环境开发过程",
      "fukuoka-central-street.steps.0.title": "搭建白盒",
      "fukuoka-central-street.steps.0.body": "建立街道网络、建筑体块与住宅内部结构。",
      "fukuoka-central-street.steps.1.title": "陈设与布光",
      "fukuoka-central-street.steps.1.body": "以组装资产、招牌和雨中黄昏灯光替换简单体块。",
      "fukuoka-central-street.steps.2.title": "呈现空间",
      "fukuoka-central-street.steps.2.body": "通过电影镜头序列呈现场景，记录 NPC 导航配置。",
      "fukuoka-central-street.roles.0.title": "街区与室内布局",
      "fukuoka-central-street.roles.0.body": "迭代白盒布局，组织室外地标与相连的住宅空间。",
      "fukuoka-central-street.roles.1.title": "环境搭建",
      "fukuoka-central-street.roles.1.body": "布置第三方模型与道具，替换白盒资产，塑造黄昏氛围。",
      "fukuoka-central-street.roles.2.title": "镜头与导航",
      "fukuoka-central-street.roles.2.body": "记录 Sequencer 镜头轨道，以及 AI Controller、NavMesh 与行为树构成的局部 NPC 移动配置。",
      "fukuoka-central-street.gallery.0": "环境资产搭建前的早期街道白盒画面。",
      "fukuoka-central-street.gallery.1": "Unreal 编辑器中的住宅内部搭建画面，布局参考《莎木》的芭月家。",
      "fukuoka-central-street.gallery.2": "项目室外 Sequencer 镜头时间轴的局部截图。",
      "fukuoka-central-street.gallery.3": "资料中的 NPC Blueprint 与行为树配置截图，用于展示实现过程，未据此声称已完成实时行为测试。",
      "fukuoka-central-street.index": "项目 05 / Fukuoka Central Street",
      "dragon-of-kamurocho.row.meta": "桌游 / 非商业学习原型",
      "dragon-of-kamurocho.row.kind": "领地与经济",
      "dragon-of-kamurocho.tagline": "每一块领地，都会改变下一次选择。",
      "dragon-of-kamurocho.status": "实体桌游原型",
      "dragon-of-kamurocho.mediaCaption": "真实实体原型地图，包含领地标记、卡牌与游戏钞票。",
      "dragon-of-kamurocho.ideaTitle": "把领地、资金与战力连接起来。",
      "dragon-of-kamurocho.lead": "一个以《如龙 / Like a Dragon》神室町为背景、用于非商业学习的粉丝启发策略桌游原型。",
      "dragon-of-kamurocho.body": "玩家通过领地产生收入、投入资金发展，并以角色战力争夺对手地盘。地区风险与中立事件时机影响扩张，规划中的千禧塔决战则为经济系统提供最终目标。设计参考了《Rurik: Dawn of Kiev》的领地兼并思路，将其与战力和资金更加紧密地连接。",
      "dragon-of-kamurocho.scope": "资料记录了实体原型、规则流程与组件开发。作品标注目标为 2–3 人、约 20 分钟；这是设计规格，未作为实测时长核实。这是非官方、非商业学习原型，不声称《如龙》IP 原创，也未提供获授权的打印发行包。",
      "dragon-of-kamurocho.roleTitle": "把相互关联的系统转化为桌面决策。",
      "dragon-of-kamurocho.roleBody": "我的工作涵盖规则与系统设计、原型地图及组件组织。我将领地控制、角色战力、收入与中立事件风险连接，再通过实体材料及规则图示呈现这些关系。角色世界观及借用美术仍属于第三方内容。",
      "dragon-of-kamurocho.galleryTitle": "让规则成为实体。",
      "dragon-of-kamurocho.credits": "《如龙 / Like a Dragon》提供粉丝启发的世界观与角色参考，其 IP 及角色美术仍属于各自权利方。《Rurik: Dawn of Kiev》是资料中记录的领地兼并设计参考。商业扑克牌、游戏钞票组件及其他借用视觉素材不作为本人原创成果。所选原型照片与流程图用于记录学习和系统设计，不授予复制相关 IP 或材料的许可，也不表示官方关联。",
      "dragon-of-kamurocho.fact.0": "桌游原型",
      "dragon-of-kamurocho.fact.1": "实体桌游",
      "dragon-of-kamurocho.fact.2": "领地、经济与风险",
      "dragon-of-kamurocho.fact.3": "规则、系统与原型组件",
      "dragon-of-kamurocho.fact.4": "2–3 人 / 设计目标",
      "dragon-of-kamurocho.loopLabel": "资料中的回合结构",
      "dragon-of-kamurocho.steps.0.title": "积累收入",
      "dragon-of-kamurocho.steps.0.body": "选择初始领地，以当地资源发展资金与能力。",
      "dragon-of-kamurocho.steps.1.title": "投资与兼并",
      "dragon-of-kamurocho.steps.1.body": "将资金与角色战力用于领地发展及所有权争夺。",
      "dragon-of-kamurocho.steps.2.title": "处理风险",
      "dragon-of-kamurocho.steps.2.body": "跟踪中立事件回合及地区风险，向规划中的最终决战推进。",
      "dragon-of-kamurocho.roles.0.title": "规则与经济",
      "dragon-of-kamurocho.roles.0.body": "将领地收入、资金支出、角色战力与兼并条件连接为决策结构。",
      "dragon-of-kamurocho.roles.1.title": "风险与时机",
      "dragon-of-kamurocho.roles.1.body": "设计地区风险等级、中立事件判定与呈现事件时机的计数标记。",
      "dragon-of-kamurocho.roles.2.title": "实体原型制作",
      "dragon-of-kamurocho.roles.2.body": "准备作品资料中展示的地图、卡牌与标记布局、规则流程及实体材料。",
      "dragon-of-kamurocho.gallery.0": "原始回合流程图，连接行动、事件、兼并与规划中的最终决战。",
      "dragon-of-kamurocho.gallery.1": "早期纸面原型，用实体标记跟踪地区事件时机。",
      "dragon-of-kamurocho.gallery.2": "组装的原型组件，包括卡牌、标记、骰子及第三方游戏钞票材料。",
      "dragon-of-kamurocho.index": "项目 06 / Yakuza — Dragon of Kamurocho"
    }
  }
};
window.PORTFOLIO.projects=collection.projects;
window.PORTFOLIO.categories=collection.categories;
for(const language of Object.keys(collection.languages)) Object.assign(window.PORTFOLIO.languages[language],collection.languages[language]);
})();
