/* Public portfolio content and category metadata. */
(()=>{
const collection={
  "categories": [
    "games",
    "levels",
    "technical",
    "narrative"
  ],
  "projects": [
    {
      "id": "wonderwebby",
      "file": "wonderwebby.html",
      "title": "Wonder Webby",
      "name": [
        "Wonder",
        "Webby"
      ],
      "categories": [
        "games",
        "technical"
      ],
      "engine": "Unity 6",
      "cover": "assets/wonderwebby-cover.webp",
      "index": 1,
      "metaKey": "wonderwebby.row.meta",
      "kindKey": "wonderwebby.row.kind"
    },
    {
      "id": "moon-vagrant",
      "file": "moon-vagrant.html",
      "title": "Moon Vagrant",
      "name": [
        "Moon",
        "Vagrant"
      ],
      "categories": [
        "games"
      ],
      "engine": "GDevelop 5",
      "cover": "assets/moon-vagrant-title.webp",
      "index": 2,
      "metaKey": "moon-vagrant.row.meta",
      "kindKey": "moon-vagrant.row.kind"
    },
    {
      "id": "fanworks",
      "file": "fanworks.html",
      "title": "FanWorks",
      "name": [
        "Fan",
        "Works"
      ],
      "categories": [
        "levels"
      ],
      "engine": "Unreal Engine 5.6",
      "cover": "assets/fanworks-overview.webp",
      "index": 3,
      "metaKey": "fanworks.row.meta",
      "kindKey": "fanworks.row.kind"
    },
    {
      "id": "ancient-courtyard",
      "file": "ancient-courtyard.html",
      "title": "Ancient Courtyard",
      "name": [
        "Ancient",
        "Courtyard"
      ],
      "categories": [
        "levels",
        "technical"
      ],
      "engine": "Unity 6",
      "cover": "assets/ancient-courtyard-route.svg",
      "index": 4,
      "metaKey": "ancient-courtyard.row.meta",
      "kindKey": "ancient-courtyard.row.kind"
    }
  ],
  "languages": {
    "en": {
      "collection.all": "All work",
      "collection.games": "Digital games",
      "collection.levels": "Levels & environments",
      "collection.technical": "Gameplay & technical prototypes",
      "collection.narrative": "Narrative & tabletop",
      "collection.filters": "Filter projects by category",
      "collection.empty.title": "A chapter still taking shape.",
      "collection.empty.body": "More work will join the collection as its story and contribution are documented.",
      "collection.empty.reset": "View all work",
      "collection.count.one": "{count} project",
      "collection.count.many": "{count} projects",
      "work.note": "Four projects, from small playable worlds to spatial experiments.",
      "v5.team": "Personal experiments and team projects, with my part in each documented.",
      "about.detail3": "Every case study separates the project from my contribution, with shared work and assets credited.",
      "case.idea.label": "01 / THE IDEA",
      "case.role.label": "02 / MY CONTRIBUTION",
      "case.gallery.label": "03 / A CLOSER LOOK",
      "case.credits.label": "04 / Credits & context",
      "case.scope": "CURRENT SCOPE",
      "case.process": "DESIGN & ITERATION",
      "case.shared": "PROJECT CONTEXT",
      "case.media.stills": "PROTOTYPE STILLS",
      "case.media.route": "SCENE ROUTE / DIAGRAM",
      "case.gallery.hint": "Select an image. Take a closer look.",
      "gallery.zoom": "Enlarge image",
      "lightbox.title": "Project image",
      "project.nav.gallery": "Images & diagrams",
      "project.end.note": "BACK TO THE COLLECTION",
      "case.fact.type": "PROJECT",
      "case.fact.engine": "ENGINE",
      "case.fact.focus": "FOCUS",
      "case.fact.role": "MY ROLE",
      "case.fact.status": "STATUS",
      "role.badge": "GAMEPLAY & CAMERA",
      "role.title": "The team’s game. My contribution.",
      "role.body": "I implemented hunting and feeding interactions, an adaptive wall-and-ceiling camera, contextual interaction prompts, and collision and interaction refinements in Unity.",
      "role.one": "Hunting & feeding",
      "role.two": "Camera & movement",
      "role.three": "Interaction & iteration",
      "role.hunt": "Developed prey collection and feeding interactions, with teammate support on the feeding work.",
      "role.camera": "Reworked camera behaviour on walls and ceilings and refined collision handling during traversal.",
      "role.interaction": "Added contextual prompts and controller interaction refinements, then addressed gameplay bugs through iteration.",
      "fact.role.value": "Gameplay & camera development",
      "case.webby.scope": "A playable team prototype in development. Sound, UI and gameplay polish continue.",
      "case.webby.credit": "Main menu UI, visual direction and typography were created by Leo. Environment, artwork and other systems are shared team contributions.",
      "case.webby.engine": "Unity 6",
      "wonderwebby.row.meta": "UNITY / TEAM PROJECT",
      "wonderwebby.row.kind": "Exploration",
      "moon-vagrant.row.meta": "GDEVELOP / SOLO PROTOTYPE",
      "moon-vagrant.row.kind": "Space survival",
      "moon-vagrant.tagline": "A small ship. A crowded sky.",
      "moon-vagrant.status": "PLAYABLE PROTOTYPE",
      "moon-vagrant.mediaCaption": "The exported prototype’s title screen.",
      "moon-vagrant.ideaTitle": "Survival, one decision at a time.",
      "moon-vagrant.lead": "A 2D space shooter built around movement, pressure and limited resources.",
      "moon-vagrant.body": "Pilot a small spacecraft through asteroids and enemy fire. Mouse-directed movement and shooting work alongside sprint and shockwave abilities, while health, fuel and weapon heat create competing demands. A comic-style introduction leads into the combat encounter.",
      "moon-vagrant.scope": "The Windows export demonstrates a compact combat slice. Full multi-level progression, advanced upgrades and complete story delivery are outside this prototype’s scope.",
      "moon-vagrant.roleTitle": "From concept to a playable slice.",
      "moon-vagrant.roleBody": "I developed the concept and prototype scope, implemented the game in GDevelop, prepared playtests, organised observations and analysed the findings.",
      "moon-vagrant.galleryTitle": "A story before the pressure.",
      "moon-vagrant.credits": "Built with GDevelop. These screenshots show the exported prototype and its existing artwork; the GDevelop watermark is retained. The development contribution described here does not claim authorship of every illustration or audio asset.",
      "moon-vagrant.index": "PROJECT 02 / MOON VAGRANT",
      "moon-vagrant.fact.0": "Individual project",
      "moon-vagrant.fact.1": "GDevelop 5",
      "moon-vagrant.fact.2": "Combat & readability",
      "moon-vagrant.fact.3": "Concept, implementation & playtesting",
      "moon-vagrant.fact.4": "Combat slice / v1.0.0",
      "moon-vagrant.steps.0.title": "Move & evade",
      "moon-vagrant.steps.0.body": "Read incoming threats and use sprint to change position.",
      "moon-vagrant.steps.1.title": "Shoot & manage",
      "moon-vagrant.steps.1.body": "Attack while keeping track of heat, health and movement resources.",
      "moon-vagrant.steps.2.title": "Survive & retry",
      "moon-vagrant.steps.2.body": "Use shockwave to respond to pressure, then learn from the encounter.",
      "moon-vagrant.roles.0.title": "Combat rules",
      "moon-vagrant.roles.0.body": "Implemented mouse-directed movement, shooting, sprint and shockwave interactions in the prototype.",
      "moon-vagrant.roles.1.title": "Story & interface",
      "moon-vagrant.roles.1.body": "Connected the title screen and comic introduction to the combat scene and resource feedback.",
      "moon-vagrant.roles.2.title": "Playtest observations",
      "moon-vagrant.roles.2.body": "Identified improvements to onboarding, resource HUD, ability feedback and boss pacing. These are iteration proposals, rather than verified completed changes.",
      "moon-vagrant.gallery.0": "The comic-style introduction in the prototype.",
      "moon-vagrant.gallery.1": "An in-game frame with the movement hint and resource HUD.",
      "moon-vagrant.loopLabel": "THE CORE LOOP",
      "fanworks.row.meta": "UNREAL / TEAM LEVEL DESIGN",
      "fanworks.row.kind": "Puzzle platforming",
      "fanworks.tagline": "Leave a body. Open a route.",
      "fanworks.status": "LEVEL PROTOTYPE",
      "fanworks.mediaCaption": "Overview of the saved FanWorks prototype.",
      "fanworks.ideaTitle": "Make familiar space work differently.",
      "fanworks.lead": "Three industrial puzzle-platforming areas built within the team’s Stack O Bot project.",
      "fanworks.body": "FanWorks uses retained robot bodies, dependent controls and changing elevation to make players plan their route. Outward journeys become return routes, lifts change access to upper spaces, and simultaneous pressure-plate states govern the final relay.",
      "fanworks.scope": "The three segments are implemented as prototype layouts. Recorded checks cover selected mechanisms and geometry; continuous traversal from Player Start, first-time navigation and completion time still need playtesting.",
      "fanworks.roleTitle": "Three segments. One spatial language.",
      "fanworks.roleBody": "I implemented Intake Maintenance, Turbine Crossing and Cascade Relay for Level 2, arranging the routes, vertical layers and local mechanism dependencies.",
      "fanworks.galleryTitle": "The same space, a new perspective.",
      "fanworks.credits": "Built within a team project using Stack O Bot assets. Existing robot movement, jumping, jetpack, body placement, checkpoint systems and shared interaction mechanisms are retained. My contribution here is the three segment implementations and their layouts.",
      "fanworks.index": "PROJECT 03 / FANWORKS",
      "fanworks.fact.0": "Team project",
      "fanworks.fact.1": "Unreal Engine 5.6",
      "fanworks.fact.2": "Spatial puzzle design",
      "fanworks.fact.3": "Three Level 2 segments",
      "fanworks.fact.4": "Prototype / playtesting pending",
      "fanworks.steps.0.title": "Intake Maintenance",
      "fanworks.steps.0.body": "Use a retained body to power airflow, then activate controls along an upper maintenance route.",
      "fanworks.steps.1.title": "Turbine Crossing",
      "fanworks.steps.1.body": "Transfer between rotating blades and landings, then find the elevated return route.",
      "fanworks.steps.2.title": "Cascade Relay",
      "fanworks.steps.2.body": "Keep pressure plates A and B active and reach the master control to enable the exit.",
      "fanworks.roles.0.title": "Route construction",
      "fanworks.roles.0.body": "Built outward and return routes with elevation changes and alternative landing areas.",
      "fanworks.roles.1.title": "Puzzle dependencies",
      "fanworks.roles.1.body": "Arranged body placement, pressure plates, buttons and lifts into dependent local sequences.",
      "fanworks.roles.2.title": "Plans & iteration",
      "fanworks.roles.2.body": "Produced segment layouts and supporting plan diagrams. The current work remains a prototype, with readability and uninterrupted traversal to be evaluated.",
      "fanworks.gallery.0": "Intake Maintenance: layered industrial platforms and airflow devices.",
      "fanworks.gallery.1": "Turbine Crossing: rotating-blade transfers and elevated return paths.",
      "fanworks.gallery.2": "Cascade Relay: the lift and upper route toward the final control.",
      "fanworks.loopLabel": "SEGMENT ROUTES",
      "ancient-courtyard.row.meta": "UNITY / COURSEWORK IMPLEMENTATION",
      "ancient-courtyard.row.kind": "Micro-experience",
      "ancient-courtyard.tagline": "Three scenes. A small journey.",
      "ancient-courtyard.status": "COURSEWORK PROTOTYPE",
      "ancient-courtyard.mediaCaption": "A schematic of the documented scene order, not a game screenshot.",
      "ancient-courtyard.ideaTitle": "An objective carries the player forward.",
      "ancient-courtyard.lead": "A small Unity experience connecting a museum, an ancient courtyard and a final project room.",
      "ancient-courtyard.body": "The player explores the scenes, collects relics and completes objectives to progress. The courtyard provides the collection encounter, while a gate interaction connects the experience to its next space.",
      "ancient-courtyard.scope": "The source project contains three enabled scenes and collection and progression scripts. This case study documents that implementation; a public playable build and final walkthrough have not been verified. Ancient Courtyard is a descriptive portfolio title.",
      "ancient-courtyard.roleTitle": "Connect the spaces. Clarify the objective.",
      "ancient-courtyard.roleBody": "I assembled the three-scene experience and integrated relic collection, objective progress and gate interactions in Unity.",
      "ancient-courtyard.galleryTitle": "A route through three spaces.",
      "ancient-courtyard.credits": "The ancient courtyard uses Ruins Constructor PBR by ice_screen. Player movement and camera use Unity Starter Assets / Third Person Controller; particle effects use the project’s credited Unity assets. These are third-party assets, rather than original models or controller systems by me.",
      "ancient-courtyard.index": "PROJECT 04 / ANCIENT COURTYARD",
      "ancient-courtyard.fact.0": "Coursework implementation",
      "ancient-courtyard.fact.1": "Unity 6",
      "ancient-courtyard.fact.2": "Collection & progression",
      "ancient-courtyard.fact.3": "Scene & gameplay integration",
      "ancient-courtyard.fact.4": "Three-scene micro-experience",
      "ancient-courtyard.steps.0.title": "Museum",
      "ancient-courtyard.steps.0.body": "Start the experience and enter the scene sequence.",
      "ancient-courtyard.steps.1.title": "Ancient Courtyard",
      "ancient-courtyard.steps.1.body": "Explore, collect relics and complete the local objective.",
      "ancient-courtyard.steps.2.title": "Project Room",
      "ancient-courtyard.steps.2.body": "Continue to the final space after objective completion.",
      "ancient-courtyard.roles.0.title": "Scene assembly",
      "ancient-courtyard.roles.0.body": "Connected the museum, collection courtyard and final room into an ordered experience.",
      "ancient-courtyard.roles.1.title": "Collection & feedback",
      "ancient-courtyard.roles.1.body": "Integrated pickup counting, objective completion and the on-screen progress display.",
      "ancient-courtyard.roles.2.title": "Interaction integration",
      "ancient-courtyard.roles.2.body": "Integrated gate interaction and scene progression with the project’s existing movement and camera assets.",
      "ancient-courtyard.gallery.0": "Museum → Ancient Courtyard → Project Room. Scene-order diagram.",
      "ancient-courtyard.loopLabel": "SCENE SEQUENCE"
    },
    "zh": {
      "collection.all": "全部作品",
      "collection.games": "数字游戏",
      "collection.levels": "关卡与场景",
      "collection.technical": "玩法与技术原型",
      "collection.narrative": "叙事与桌游",
      "collection.filters": "按类别筛选作品",
      "collection.empty.title": "这一章，仍在整理中。",
      "collection.empty.body": "待作品背景与个人贡献整理清楚后，这里会加入更多作品。",
      "collection.empty.reset": "查看全部作品",
      "collection.count.one": "{count} 个项目",
      "collection.count.many": "{count} 个项目",
      "work.note": "四个项目，从可玩的微型世界，到空间与玩法实验。",
      "v5.team": "个人探索与团队项目，分别记录我在其中承担的工作。",
      "about.detail3": "每个案例都分别介绍作品和我的贡献，并注明团队工作与使用的素材。",
      "case.idea.label": "01 / 作品构想",
      "case.role.label": "02 / 我的贡献",
      "case.gallery.label": "03 / 近看作品",
      "case.credits.label": "04 / 署名与背景",
      "case.scope": "当前范围",
      "case.process": "设计与迭代",
      "case.shared": "项目背景",
      "case.media.stills": "原型截图",
      "case.media.route": "场景路线 / 示意图",
      "case.gallery.hint": "选择图片，查看细节。",
      "gallery.zoom": "放大图片",
      "lightbox.title": "项目图片",
      "project.nav.gallery": "图片与图示",
      "project.end.note": "回到作品集",
      "case.fact.type": "项目形式",
      "case.fact.engine": "引擎",
      "case.fact.focus": "设计重点",
      "case.fact.role": "我的职责",
      "case.fact.status": "当前状态",
      "role.badge": "玩法与相机",
      "role.title": "团队的作品，我的贡献。",
      "role.body": "我在 Unity 中实现捕猎与喂食交互、适应墙壁与天花板的相机、情境交互提示，并完善碰撞和交互体验。",
      "role.one": "捕猎与喂食",
      "role.two": "相机与移动",
      "role.three": "交互与迭代",
      "role.hunt": "开发猎物收集和喂食交互，喂食部分有队友协作。",
      "role.camera": "重做墙壁与天花板上的相机行为，并改善移动过程中的碰撞处理。",
      "role.interaction": "加入情境提示、完善手柄交互，并在迭代中修正玩法问题。",
      "fact.role.value": "玩法与相机开发",
      "case.webby.scope": "开发中的团队可玩原型，音效、界面和玩法仍在打磨。",
      "case.webby.credit": "主菜单界面、视觉方向和字体设计由 Leo 完成；环境、美术和其他系统属于团队共同成果。",
      "case.webby.engine": "Unity 6",
      "wonderwebby.row.meta": "UNITY / 团队项目",
      "wonderwebby.row.kind": "探索",
      "moon-vagrant.row.meta": "GDEVELOP / 个人原型",
      "moon-vagrant.row.kind": "太空生存",
      "moon-vagrant.tagline": "一艘小船，一片危机四伏的天空。",
      "moon-vagrant.status": "可玩原型",
      "moon-vagrant.mediaCaption": "导出原型的标题画面。",
      "moon-vagrant.ideaTitle": "在每一次选择中求生。",
      "moon-vagrant.lead": "围绕移动、压力与有限资源构建的 2D 太空射击原型。",
      "moon-vagrant.body": "驾驶小型飞船穿越小行星与敌方火力。鼠标移动与射击配合冲刺、冲击波能力，生命、燃料与武器热量形成不同的资源压力；漫画式开场引入战斗遭遇。",
      "moon-vagrant.scope": "Windows 导出版本展示一个紧凑的战斗切片，未覆盖完整多关卡进程、进阶升级或完整故事。",
      "moon-vagrant.roleTitle": "从概念，到可玩的切片。",
      "moon-vagrant.roleBody": "我完成概念与原型范围设计，在 GDevelop 中实现游戏，并准备试玩、整理观察记录和分析结果。",
      "moon-vagrant.galleryTitle": "压力来临前，故事先开始。",
      "moon-vagrant.credits": "使用 GDevelop 制作。截图来自导出原型，保留原有画面与 GDevelop 水印；此处的开发贡献不代表所有插画或音频素材均为本人原创。",
      "moon-vagrant.index": "项目 02 / Moon Vagrant",
      "moon-vagrant.fact.0": "个人项目",
      "moon-vagrant.fact.1": "GDevelop 5",
      "moon-vagrant.fact.2": "战斗与可读性",
      "moon-vagrant.fact.3": "概念、实现与试玩分析",
      "moon-vagrant.fact.4": "战斗切片 / v1.0.0",
      "moon-vagrant.steps.0.title": "移动与闪避",
      "moon-vagrant.steps.0.body": "观察来袭威胁，用冲刺改变位置。",
      "moon-vagrant.steps.1.title": "射击与管理",
      "moon-vagrant.steps.1.body": "进攻时关注热量、生命与移动资源。",
      "moon-vagrant.steps.2.title": "生存与重试",
      "moon-vagrant.steps.2.body": "用冲击波应对压力，从遭遇中学习并重试。",
      "moon-vagrant.roles.0.title": "战斗规则",
      "moon-vagrant.roles.0.body": "在原型中实现鼠标控制移动、射击、冲刺和冲击波交互。",
      "moon-vagrant.roles.1.title": "叙事与界面",
      "moon-vagrant.roles.1.body": "连接标题画面、漫画开场、战斗场景与资源反馈。",
      "moon-vagrant.roles.2.title": "试玩观察",
      "moon-vagrant.roles.2.body": "识别引导、资源 HUD、能力反馈和 Boss 节奏的改进方向。这些是迭代建议，尚不能视为已验证完成的修改。",
      "moon-vagrant.gallery.0": "原型中的漫画式开场。",
      "moon-vagrant.gallery.1": "包含移动提示与资源 HUD 的实机画面。",
      "moon-vagrant.loopLabel": "核心循环",
      "fanworks.row.meta": "UNREAL / 团队关卡设计",
      "fanworks.row.kind": "解谜平台",
      "fanworks.tagline": "留下一具机体，打开一条路径。",
      "fanworks.status": "关卡原型",
      "fanworks.mediaCaption": "已保存的 FanWorks 原型总览。",
      "fanworks.ideaTitle": "让熟悉的空间产生新用途。",
      "fanworks.lead": "在团队 Stack O Bot 项目中实现的三个工业解谜平台区段。",
      "fanworks.body": "FanWorks 利用保留的机器人机体、相互依赖的控制装置和高度变化，引导玩家规划路径。向外的行程转化为回返路线，升降装置改变高处空间的可达性，同时保持的压力板状态决定最终接力。",
      "fanworks.scope": "三个区段已实现为原型布局。已有记录检查了部分机关和几何；从 Player Start 连续通关、首次导航体验和完成时长仍需试玩验证。",
      "fanworks.roleTitle": "三个区段，一套空间语言。",
      "fanworks.roleBody": "我负责 Level 2 的 Intake Maintenance、Turbine Crossing 和 Cascade Relay 三个区段实现，组织路线、垂直层次和局部机关依赖。",
      "fanworks.galleryTitle": "同一空间，不同视角。",
      "fanworks.credits": "基于团队项目及 Stack O Bot 素材制作，沿用已有机器人移动、跳跃、喷气背包、机体摆放、检查点和共享交互机制。此处展示的本人贡献是三个区段的实现与布局。",
      "fanworks.index": "项目 03 / FanWorks",
      "fanworks.fact.0": "团队项目",
      "fanworks.fact.1": "Unreal Engine 5.6",
      "fanworks.fact.2": "空间解谜",
      "fanworks.fact.3": "Level 2 的三个区段",
      "fanworks.fact.4": "原型 / 待持续试玩",
      "fanworks.steps.0.title": "进气维护区",
      "fanworks.steps.0.body": "以保留机体驱动气流，再沿上层维护路线激活控制装置。",
      "fanworks.steps.1.title": "涡轮跨越区",
      "fanworks.steps.1.body": "在旋转叶片与落脚区之间转移，再寻找高处的回返路线。",
      "fanworks.steps.2.title": "级联接力区",
      "fanworks.steps.2.body": "保持 A、B 压力板激活，并抵达总控制装置以开启出口。",
      "fanworks.roles.0.title": "路线构建",
      "fanworks.roles.0.body": "结合高度变化与替代落脚区，构建向外及回返路线。",
      "fanworks.roles.1.title": "解谜依赖",
      "fanworks.roles.1.body": "将机体摆放、压力板、按钮和升降装置组织为相互依赖的局部序列。",
      "fanworks.roles.2.title": "平面图与迭代",
      "fanworks.roles.2.body": "制作区段布局及辅助平面图。当前仍为原型，空间可读性与连续通行体验有待评估。",
      "fanworks.gallery.0": "进气维护区：分层工业平台与气流装置。",
      "fanworks.gallery.1": "涡轮跨越区：旋转叶片转移与高处回返路径。",
      "fanworks.gallery.2": "级联接力区：通向最终控制装置的升降机与上层路线。",
      "fanworks.loopLabel": "区段路线",
      "ancient-courtyard.row.meta": "UNITY / 课程实践",
      "ancient-courtyard.row.kind": "微体验",
      "ancient-courtyard.tagline": "三个场景，一段小小的旅程。",
      "ancient-courtyard.status": "课程原型",
      "ancient-courtyard.mediaCaption": "依据项目场景顺序绘制的路线示意图，并非游戏截图。",
      "ancient-courtyard.ideaTitle": "用目标连接玩家的旅程。",
      "ancient-courtyard.lead": "连接博物馆、古庭院与最终展示房间的 Unity 微体验。",
      "ancient-courtyard.body": "玩家探索场景、收集遗物，并通过完成目标推进流程。庭院承担收集遭遇，门的交互将体验连接到下一处空间。",
      "ancient-courtyard.scope": "源项目包含三个启用场景，以及收集与流程推进脚本。本案例记录这些实现；尚未核实公开可玩版本与最终完整 walkthrough。“Ancient Courtyard”是作品集中的描述性标题。",
      "ancient-courtyard.roleTitle": "连接空间，让目标清晰可见。",
      "ancient-courtyard.roleBody": "我在 Unity 中组织三个场景的体验，并整合遗物收集、目标进度和门的交互。",
      "ancient-courtyard.galleryTitle": "穿过三个空间的路线。",
      "ancient-courtyard.credits": "古庭院使用 ice_screen 的 Ruins Constructor PBR；玩家移动与相机使用 Unity Starter Assets / Third Person Controller，粒子效果使用项目署名表中的 Unity 素材。这些属于第三方素材，并非本人原创模型或控制器系统。",
      "ancient-courtyard.index": "项目 04 / Ancient Courtyard",
      "ancient-courtyard.fact.0": "课程实践",
      "ancient-courtyard.fact.1": "Unity 6",
      "ancient-courtyard.fact.2": "收集与流程推进",
      "ancient-courtyard.fact.3": "场景与玩法整合",
      "ancient-courtyard.fact.4": "三场景微体验",
      "ancient-courtyard.steps.0.title": "博物馆",
      "ancient-courtyard.steps.0.body": "开始体验，进入场景序列。",
      "ancient-courtyard.steps.1.title": "古庭院",
      "ancient-courtyard.steps.1.body": "探索、收集遗物，完成当前目标。",
      "ancient-courtyard.steps.2.title": "展示房间",
      "ancient-courtyard.steps.2.body": "完成目标后，进入最终空间。",
      "ancient-courtyard.roles.0.title": "场景组织",
      "ancient-courtyard.roles.0.body": "将博物馆、收集庭院与最终房间组织为有序的体验。",
      "ancient-courtyard.roles.1.title": "收集与反馈",
      "ancient-courtyard.roles.1.body": "整合拾取计数、目标完成状态和画面中的进度显示。",
      "ancient-courtyard.roles.2.title": "交互整合",
      "ancient-courtyard.roles.2.body": "将门的交互、场景推进与项目已有的移动和相机素材整合。",
      "ancient-courtyard.gallery.0": "博物馆 → 古庭院 → 展示房间。场景顺序示意图。",
      "ancient-courtyard.loopLabel": "场景顺序"
    }
  }
};
window.PORTFOLIO.projects=collection.projects;
window.PORTFOLIO.categories=collection.categories;
for(const language of Object.keys(collection.languages)) Object.assign(window.PORTFOLIO.languages[language],collection.languages[language]);
})();
