/* Public content only. Blank contact and role fields are intentional. */
window.PORTFOLIO = {
  "profile": {
    "name": "Rong Guo",
    "email": "",
    "resumeUrl": ""
  },
  "defaultLanguage": "en",
  "languages": {
    "en": {
      "nav.work": "Games",
      "nav.about": "About",
      "nav.contact": "Contact",
      "nav.menu": "Open navigation",
      "brand.discipline": "GAME DESIGN",
      "skip": "Skip to content",
      "hero.eyebrow": "GAMES / WORLDS / INTERACTIVE EXPERIENCES",
      "hero.line1": "Small ideas.",
      "hero.line2": "Playable worlds.",
      "hero.intro": "I’m {name}. A collection of games I’ve worked on, and the ideas that bring them to life.",
      "hero.link": "Explore the work",
      "hero.index": "SELECTED GAME PROJECTS",
      "work.label": "( SELECTED WORK )",
      "work.note": "One featured project. Two spaces for what comes next.",
      "featured.index": "( ONE )",
      "featured.status": "IN DEVELOPMENT",
      "featured.tagline": "Leave a little wonder behind.",
      "featured.summary": "Explore a greenhouse, weave new paths and turn a spider’s journey into art.",
      "featured.view": "Explore the project",
      "tag.team": "Team project",
      "tag.explore": "Exploration",
      "tag.web": "Web weaving",
      "placeholder.label": "DETAILS TO COME",
      "placeholder.two": "Project 02",
      "placeholder.three": "Project 03",
      "placeholder.note": "A place for a future game project. Details, imagery and a case study will appear here.",
      "placeholder.status": "TO BE ADDED",
      "about.label": "( BEHIND THE WORK )",
      "about.line1": "The work.",
      "about.line2": "The thinking.",
      "about.body": "I’m {name}. Here, the game is only part of the story.",
      "about.note": "This portfolio brings together the games I take part in and the ideas behind them. Each project leaves room for the work itself, the process and my contribution.",
      "about.focus": "WHAT YOU’LL FIND HERE",
      "about.focus1": "Game projects",
      "about.focus2": "Design thinking",
      "about.focus3": "Development notes",
      "contact.label": "( A CONVERSATION )",
      "contact.title": "Let’s talk games.",
      "contact.pending": "Contact details to be added.",
      "contact.email": "Email me",
      "contact.cv": "View résumé",
      "footer.note": "Game projects & the ideas behind them.",
      "footer.top": "Back to top",
      "footer.version": "PORTFOLIO — V",
      "project.back": "Back to selected work",
      "project.index": "PROJECT 01 / WONDER WEBBY",
      "project.tagline": "A small spider. An unexpected canvas.",
      "fact.type": "PROJECT",
      "fact.type.value": "Team project",
      "fact.brief": "BRIEF",
      "fact.brief.value": "IGB200 / QAGOMA",
      "fact.team": "TEAM",
      "fact.team.value": "6 members",
      "fact.role": "MY ROLE",
      "fact.role.value": "Team member",
      "fact.status": "STATUS",
      "fact.status.value": "In development",
      "video.label": "PROTOTYPE GAMEPLAY",
      "video.play": "Play gameplay clip",
      "video.caption": "Silent prototype recordings from the team presentation.",
      "video.one": "Web forming",
      "video.two": "Hunting & feeding",
      "video.three": "The final reveal",
      "video.fallback": "Your browser cannot play this video. Open the video file instead.",
      "overview.label": "( 01 — THE IDEA )",
      "overview.title": "A garden at spider scale.",
      "overview.lead": "Wonder Webby turns a spider’s movement into a record of play.",
      "overview.body": "Players explore a greenhouse, connect objects with silk, catch insects and return to feed spiderlings. As the routes overlap, a web grows across the space. What begins as a way to move becomes an artwork.",
      "overview.inspiration": "The team project responds to a QAGOMA brief and takes inspiration from Sandra Selig’s “Webs from my garden”.",
      "loop.label": "THE CORE LOOP",
      "loop.one.title": "Explore & weave",
      "loop.one.body": "Find anchor points and connect the space with new silk routes.",
      "loop.two.title": "Hunt & collect",
      "loop.two.body": "Use the web network to reach and catch insects.",
      "loop.three.title": "Return & feed",
      "loop.three.body": "Follow existing routes back, feed the spiderlings, and expand the network.",
      "gallery.label": "( 03 — IN THE GREENHOUSE )",
      "gallery.title": "A different way to see the world.",
      "gallery.hint": "Select a frame. Take a closer look.",
      "gallery.one": "Webby exploring the greenhouse structure.",
      "gallery.two": "Web routes woven across the play space.",
      "gallery.zoom": "Enlarge screenshot",
      "role.label": "( 02 — MY CONTRIBUTION )",
      "role.badge": "DETAILS TO ADD",
      "role.title": "The team’s game. My contribution.",
      "role.body": "I participated in Wonder Webby as a team member. This section is reserved for my responsibilities, design decisions and development process.",
      "role.one": "Role & ownership",
      "role.two": "Design decisions",
      "role.three": "Iteration & results",
      "role.pending": "To be added",
      "credits.label": "04 / Credits & source material",
      "credits.team": "THE WONDER WEBBY TEAM",
      "credits.media": "The screenshots and gameplay clips come from the Wonder Webby team presentation. They show a recorded prototype, not a browser-playable game.",
      "credits.source": "Project background: teammate Alex Roper’s project page. Individual contributions described there belong to Alex, not to me.",
      "credits.link": "Visit the external project page",
      "credits.original": "Original supplied link",
      "end.title": "Back to the bigger picture.",
      "end.link": "All selected work",
      "lightbox.close": "Close image",
      "lightbox.title": "Project screenshot",
      "clip.one.note": "Making connections between anchor points.",
      "clip.two.note": "Using the web to move and collect prey.",
      "clip.three.note": "Seeing the web as a complete artwork.",
      "noscript": "JavaScript is off. The English pages, links and native video controls still work; language switching and image zoom need JavaScript.",
      "hero.greeting": "Hi, I’m",
      "hero.current": "FEATURED WORLD / 001",
      "hero.current.caption": "A little spider. An unexpected canvas.",
      "hero.note": "Move your cursor. Follow the threads.",
      "work.title": "Games, in focus.",
      "featured.scope": "IGB200 / QAGOMA — TEAM PROJECT",
      "featured.play": "Watch gameplay",
      "featured.media.note": "PROTOTYPE FOOTAGE / SILENT",
      "featured.footnote": "Recorded gameplay, not a browser-playable game.",
      "more.label": "The next chapters.",
      "more.note": "Reserved for additional projects.",
      "about.line3": "My part.",
      "project.nav.label": "PROJECT INDEX",
      "project.nav.overview": "The idea",
      "project.nav.role": "My contribution",
      "project.nav.gallery": "Screenshots",
      "project.nav.credits": "Credits",
      "project.end.note": "END OF PROJECT / 001",
      "video.replay": "Replay clip",
      "video.error": "The clip could not be played. Please use the video controls or open the source file.",
      "lightbox.prev": "Previous screenshot",
      "lightbox.next": "Next screenshot",
      "about.accordion1": "The game",
      "about.accordion2": "The process",
      "about.accordion3": "My part",
      "about.detail1": "The worlds, mechanics and experiences at the centre of each project. Start with Wonder Webby to see the game in motion.",
      "about.detail2": "A space for prototypes, design choices and changes made along the way. More development notes will be added as the portfolio grows.",
      "about.detail3": "Team projects are shown as team projects. My responsibilities and individual contribution will be documented separately; Wonder Webby’s contribution section is still to be completed.",
      "about.small": "GAMES / IDEAS / ITERATION",
      "contact.line1": "Let’s talk",
      "contact.line2": "about play.",
      "motion.on": "MOTION ON",
      "motion.off": "MOTION OFF",
      "motion.reduced": "REDUCED MOTION",
      "motion.label": "Toggle decorative motion",
      "hero.hover": "HOVER FOR A GLIMPSE",
      "hero.touch": "EXPLORE THE PROJECT",
      "cursor.open": "EXPLORE",
      "cursor.zoom": "VIEW",
      "hero.scroll": "SCROLL TO EXPLORE",
      "work.chip": "FEATURED TEAM PROJECT",
      "hero.orb": "A WORLD IN THE MAKING",
      "hero.orbHint": "FOLLOW THE LIGHT",
      "hero.cjk": "作品集",
      "fragments.label": "( FRAGMENTS OF PLAY )",
      "fragments.line1": "Small worlds.",
      "fragments.line2": "Lasting traces.",
      "fragments.note": "A closer look at Wonder Webby, through moments from the game.",
      "fragments.link": "Inside the project",
      "fragments.one": "01 — FIND A PATH",
      "fragments.two": "02 — LEAVE A TRACE",
      "fragments.three": "03 — SEE IT DIFFERENTLY",
      "fragments.four": "04 — MAKE A CONNECTION",
      "nav.home": "Home",
      "nav.close": "Close navigation",
      "menu.label": "( INDEX )",
      "menu.note": "Games. Ideas. The spaces in between.",
      "menu.home": "HOME",
      "menu.work": "WORK",
      "menu.about": "ABOUT",
      "menu.contact": "CONTACT",
      "cursor.play": "PLAY",
      "lightbox.original": "Original game screenshot",
      "menu.title": "Site navigation",
      "v5.edition": "A STUDY IN PLAY — SELECTED GAME PROJECTS",
      "v5.skip": "Go straight to the games",
      "v5.orbHint": "MOVE YOUR CURSOR · FOLLOW THE THREAD",
      "v5.scroll": "SCROLL TO UNFOLD",
      "v5.scene": "A small world. An unexpected canvas.",
      "v5.worldNote": "WONDER WEBBY · SILENT PROTOTYPE FOOTAGE",
      "v5.traces": "( A JOURNEY IN THREE MOMENTS )",
      "v5.tracesTitle": "Every journey",
      "v5.tracesEm": "leaves a trace.",
      "v5.chapter1a": "Find a",
      "v5.chapter1b": "new path.",
      "v5.chapter1text": "Explore a greenhouse from a spider’s point of view. The ordinary becomes unfamiliar.",
      "v5.chapter2a": "Connect",
      "v5.chapter2b": "the spaces.",
      "v5.chapter2text": "Weave routes between objects. Hunt, return and build on the paths you leave behind.",
      "v5.chapter3a": "See what",
      "v5.chapter3b": "remains.",
      "v5.chapter3text": "The web begins as a tool. Seen as a whole, every journey becomes part of an artwork.",
      "v5.case": "Read the project story",
      "v5.phase1": "EXPLORE",
      "v5.phase2": "CONNECT",
      "v5.phase3": "REVEAL",
      "v5.timeline": "SCROLL OR SELECT A MOMENT",
      "v5.workTitle": "The playable collection.",
      "v5.placeholder": "A space for the next story.",
      "v5.about1": "Not just the world.",
      "v5.about2": "The way it feels",
      "v5.about3": "to be inside it.",
      "v5.team": "Wonder Webby is a team project. My individual responsibilities will be added to its project page."
    },
    "zh": {
      "nav.work": "游戏作品",
      "nav.about": "关于",
      "nav.contact": "联系",
      "nav.menu": "打开导航",
      "brand.discipline": "游戏设计",
      "skip": "跳到主要内容",
      "hero.eyebrow": "游戏 / 世界 / 互动体验",
      "hero.line1": "从小小灵感，",
      "hero.line2": "到可玩的世界。",
      "hero.intro": "我是 {name}。这里收录我参与的游戏项目，以及让这些世界成为可能的想法。",
      "hero.link": "浏览作品",
      "hero.index": "精选游戏项目",
      "work.label": "（ 精选作品 ）",
      "work.note": "一个代表项目，两个留给后续作品的位置。",
      "featured.index": "（ 一 ）",
      "featured.status": "开发中",
      "featured.tagline": "让每次探索，都留下痕迹。",
      "featured.summary": "在温室里探索，用蛛丝编织新路线，让小蜘蛛的旅程成为一件作品。",
      "featured.view": "查看项目详情",
      "tag.team": "团队项目",
      "tag.explore": "探索",
      "tag.web": "蛛网编织",
      "placeholder.label": "内容待补充",
      "placeholder.two": "项目 02",
      "placeholder.three": "项目 03",
      "placeholder.note": "这里预留给后续的游戏项目，之后将补充项目介绍、画面与详细记录。",
      "placeholder.status": "内容待补充",
      "about.label": "（ 作品背后 ）",
      "about.line1": "游戏本身，",
      "about.line2": "思考过程，",
      "about.body": "我是 {name}。游戏本身，只是故事的一部分。",
      "about.note": "这里展示我参与的游戏，也记录它们背后的想法。每个项目都为作品、开发过程与我的贡献留出空间。",
      "about.focus": "作品集内容",
      "about.focus1": "游戏项目",
      "about.focus2": "设计思考",
      "about.focus3": "开发记录",
      "contact.label": "（ 开始对话 ）",
      "contact.title": "聊聊游戏。",
      "contact.pending": "联系方式待补充。",
      "contact.email": "发送邮件",
      "contact.cv": "查看简历",
      "footer.note": "游戏项目，以及背后的想法。",
      "footer.top": "回到顶部",
      "footer.version": "作品集 — V",
      "project.back": "返回精选作品",
      "project.index": "项目 01 / WONDER WEBBY",
      "project.tagline": "一只小蜘蛛，一张意想不到的画布。",
      "fact.type": "项目类型",
      "fact.type.value": "团队项目",
      "fact.brief": "项目课题",
      "fact.brief.value": "IGB200 / QAGOMA",
      "fact.team": "团队规模",
      "fact.team.value": "6 人",
      "fact.role": "我的身份",
      "fact.role.value": "团队成员",
      "fact.status": "项目状态",
      "fact.status.value": "开发中",
      "video.label": "原型实机演示",
      "video.play": "播放实机片段",
      "video.caption": "来自团队演示文件的无声原型录屏。",
      "video.one": "蛛网构建",
      "video.two": "捕猎与喂养",
      "video.three": "最终揭示",
      "video.fallback": "浏览器不支持播放此视频，请直接打开视频文件。",
      "overview.label": "（ 一 · 项目想法 ）",
      "overview.title": "从蜘蛛的尺度，探索花园。",
      "overview.lead": "Wonder Webby 将蜘蛛的移动，变成游玩过程的记录。",
      "overview.body": "玩家在温室中探索，用蛛丝连接物体，捕捉昆虫，再返回喂养幼蛛。随着路线不断交叠，蛛网逐渐铺满空间。起初用于移动的工具，最终成为一件作品。",
      "overview.inspiration": "这是回应 QAGOMA 课题的团队项目，灵感来自 Sandra Selig 的《Webs from my garden》。",
      "loop.label": "核心玩法循环",
      "loop.one.title": "探索与织网",
      "loop.one.body": "寻找锚点，用新的蛛丝路线连接空间。",
      "loop.two.title": "捕猎与收集",
      "loop.two.body": "利用蛛网接近并捕捉昆虫。",
      "loop.three.title": "返回与喂养",
      "loop.three.body": "沿已有路线返回，喂养幼蛛，再继续扩展蛛网。",
      "gallery.label": "（ 三 · 温室之中 ）",
      "gallery.title": "换一种方式，看这个世界。",
      "gallery.hint": "选择一帧，看看细节。",
      "gallery.one": "Webby 在温室框架上探索。",
      "gallery.two": "在游玩空间中不断交叠的蛛网路线。",
      "gallery.zoom": "放大截图",
      "role.label": "（ 二 · 我的贡献 ）",
      "role.badge": "内容待补充",
      "role.title": "团队的游戏，我负责的部分。",
      "role.body": "我作为团队成员参与了 Wonder Webby。这里预留给我的具体职责、设计选择和开发过程。",
      "role.one": "负责范围",
      "role.two": "设计选择",
      "role.three": "迭代与结果",
      "role.pending": "待补充",
      "credits.label": "04 / 团队署名与素材来源",
      "credits.team": "WONDER WEBBY 项目团队",
      "credits.media": "截图与实机片段来自 Wonder Webby 团队演示文件。它们展示的是录制时的原型，不是可在网页中直接游玩的游戏。",
      "credits.source": "项目背景参考队友 Alex Roper 的项目页面。该页面描述的个人贡献属于 Alex，没有写成我的工作。",
      "credits.link": "查看外部项目介绍",
      "credits.original": "用户提供的原链接",
      "end.title": "回到作品集，继续探索。",
      "end.link": "全部精选作品",
      "lightbox.close": "关闭大图",
      "lightbox.title": "项目截图",
      "clip.one.note": "通过锚点建立新的蛛丝连接。",
      "clip.two.note": "利用蛛网移动并收集猎物。",
      "clip.three.note": "将整个蛛网作为一件作品来观看。",
      "noscript": "JavaScript 未启用。英文页面、链接和原生视频控件仍可使用；语言切换和图片放大需要启用 JavaScript。",
      "hero.greeting": "你好，我是",
      "hero.current": "代表作品 / 001",
      "hero.current.caption": "一只小蜘蛛，一张意想不到的画布。",
      "hero.note": "移动鼠标，感受蛛丝的回应。",
      "work.title": "让游戏成为主角。",
      "featured.scope": "IGB200 / QAGOMA — 团队项目",
      "featured.play": "观看实机片段",
      "featured.media.note": "原型录屏 / 无声",
      "featured.footnote": "这是录制的实机片段，不是网页版游戏。",
      "more.label": "接下来的篇章。",
      "more.note": "为后续游戏项目预留。",
      "about.line3": "我的部分。",
      "project.nav.label": "项目索引",
      "project.nav.overview": "项目想法",
      "project.nav.role": "我的贡献",
      "project.nav.gallery": "游戏截图",
      "project.nav.credits": "团队署名",
      "project.end.note": "项目结束 / 001",
      "video.replay": "重新播放",
      "video.error": "暂时无法播放，请使用视频控件或直接打开视频文件。",
      "lightbox.prev": "上一张截图",
      "lightbox.next": "下一张截图",
      "about.accordion1": "游戏本身",
      "about.accordion2": "设计过程",
      "about.accordion3": "我的贡献",
      "about.detail1": "每个项目的世界、玩法与体验。你可以从 Wonder Webby 开始，通过实机片段了解这个游戏。",
      "about.detail2": "这里会记录原型、设计选择和开发中的调整。随着作品集的完善，开发过程也会逐步补充。",
      "about.detail3": "团队作品会明确标为团队项目。我的职责和个人贡献会单独说明；Wonder Webby 的具体分工仍待补充。",
      "about.small": "游戏 / 想法 / 迭代",
      "contact.line1": "一起聊聊，",
      "contact.line2": "关于游戏。",
      "motion.on": "动效开启",
      "motion.off": "动效关闭",
      "motion.reduced": "减少动态效果",
      "motion.label": "开启或关闭装饰动效",
      "hero.hover": "悬停预览实机",
      "hero.touch": "走进这个项目",
      "cursor.open": "探索",
      "cursor.zoom": "查看",
      "hero.scroll": "向下探索",
      "work.chip": "团队代表项目",
      "hero.orb": "一个世界，正在成形",
      "hero.orbHint": "循着光，走进作品",
      "hero.cjk": "作品集",
      "fragments.label": "（ 游玩的片刻 ）",
      "fragments.line1": "小小世界，",
      "fragments.line2": "留下痕迹。",
      "fragments.note": "从游戏中的几个片刻，走近 Wonder Webby。",
      "fragments.link": "走进这个项目",
      "fragments.one": "一 · 寻找路径",
      "fragments.two": "二 · 留下痕迹",
      "fragments.three": "三 · 换个视角",
      "fragments.four": "四 · 建立连接",
      "nav.home": "首页",
      "nav.close": "关闭导航",
      "menu.label": "（ 目录 ）",
      "menu.note": "游戏，想法，以及它们之间的探索。",
      "menu.home": "HOME",
      "menu.work": "WORK",
      "menu.about": "ABOUT",
      "menu.contact": "CONTACT",
      "cursor.play": "播放",
      "lightbox.original": "游戏原始截图",
      "menu.title": "网站导航",
      "v5.edition": "关于游玩的探索 — 游戏项目作品集",
      "v5.skip": "直接浏览游戏作品",
      "v5.orbHint": "移动鼠标 · 跟随丝线",
      "v5.scroll": "向下滚动，展开故事",
      "v5.scene": "微小的世界，意想不到的画布。",
      "v5.worldNote": "WONDER WEBBY · 无声原型实录",
      "v5.traces": "（ 三个瞬间，一段旅程 ）",
      "v5.tracesTitle": "每一次探索，",
      "v5.tracesEm": "都会留下痕迹。",
      "v5.chapter1a": "寻找",
      "v5.chapter1b": "新的路径。",
      "v5.chapter1text": "用蜘蛛的视角探索温室。熟悉的环境，变成一个陌生的世界。",
      "v5.chapter2a": "连接",
      "v5.chapter2b": "彼此的空间。",
      "v5.chapter2text": "在物体间编织丝线，捕猎、返回，沿着留下的路径继续探索。",
      "v5.chapter3a": "看见",
      "v5.chapter3b": "留下的痕迹。",
      "v5.chapter3text": "蛛网起初是移动的工具。当你看见它的全貌，每次旅程都成为作品的一部分。",
      "v5.case": "查看完整项目",
      "v5.phase1": "探索",
      "v5.phase2": "连接",
      "v5.phase3": "回望",
      "v5.timeline": "滚动浏览，或选择一个瞬间",
      "v5.workTitle": "可以游玩的故事。",
      "v5.placeholder": "留给下一个故事的位置。",
      "v5.about1": "不只是一个世界。",
      "v5.about2": "也关乎置身其中，",
      "v5.about3": "是一种什么感受。",
      "v5.team": "Wonder Webby 为团队项目。我的具体分工将在项目详情页单独补充。"
    }
  },
  "clips": [
    {
      "src": "assets/slide5_web_forming.mp4",
      "poster": "assets/slide5_web_forming.webp",
      "duration": "0:16",
      "labelKey": "video.one",
      "noteKey": "clip.one.note"
    },
    {
      "src": "assets/slide6_hunting_feeding.mp4",
      "poster": "assets/slide6_hunting_feeding.webp",
      "duration": "0:16",
      "labelKey": "video.two",
      "noteKey": "clip.two.note"
    },
    {
      "src": "assets/slide7_final_reveal.mp4",
      "poster": "assets/slide7_final_reveal.webp",
      "duration": "0:20",
      "labelKey": "video.three",
      "noteKey": "clip.three.note"
    }
  ]
};